In [1]:
import tensorflow

In [2]:
from tensorflow import keras

In [3]:
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt

In [12]:
import pandas as pd

In [13]:
df=pd.read_csv("train.csv")

In [14]:
df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [15]:
x=df.drop("label",axis=1)

In [16]:
y=df["label"]

In [8]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
x.shape

(42000, 784)

In [18]:
y.shape

(42000,)

In [19]:
y

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [20]:
y

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2 , random_state= 42)

In [23]:
from sklearn.preprocessing import LabelBinarizer
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical

In [31]:
X_train, X_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

In [32]:
X_train.shape

(33600, 784)

In [33]:
X_train=X_train.values.reshape(-1,28,28,1)/255.0


In [34]:
X_val = X_val.values.reshape(-1, 28, 28, 1) / 255.0

In [35]:
model=Sequential()

In [37]:
model.add(Conv2D(32,kernel_size=(3,3),activation="relu",input_shape=(28,28,1)))

In [38]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [39]:
model.add(Conv2D(64,kernel_size=(3,3),activation="relu"))

In [40]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [41]:
model.add(Conv2D(64,kernel_size=(3,3),activation="relu"))

In [42]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [43]:
model.add(Flatten())

In [44]:
model.add(Dense(128,activation="relu"))
model.add(Dense(10,activation="softmax"))

In [46]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 1, 1, 64)         0

In [47]:
early_stopping = EarlyStopping(patience=3, restore_best_weights=True)

In [67]:
y_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [48]:
label_binarizer = LabelBinarizer()
y_train = label_binarizer.fit_transform(y_train)
y_val = label_binarizer.transform(y_val)

In [50]:
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

In [51]:
history=model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_val,y_val),callbacks=[early_stopping])

Epoch 1/100
1050/1050 [==============================] - 16s 15ms/step - loss: 0.2868 - accuracy: 0.9095 - val_loss: 0.1263 - val_accuracy: 0.9621
Epoch 2/100
1050/1050 [==============================] - 15s 14ms/step - loss: 0.0903 - accuracy: 0.9717 - val_loss: 0.0705 - val_accuracy: 0.9786
Epoch 3/100
1050/1050 [==============================] - 15s 14ms/step - loss: 0.0647 - accuracy: 0.9799 - val_loss: 0.0575 - val_accuracy: 0.9819
Epoch 4/100
1050/1050 [==============================] - 15s 14ms/step - loss: 0.0519 - accuracy: 0.9837 - val_loss: 0.0664 - val_accuracy: 0.9799
Epoch 5/100
1050/1050 [==============================] - 15s 14ms/step - loss: 0.0406 - accuracy: 0.9876 - val_loss: 0.0712 - val_accuracy: 0.9777
Epoch 6/100
1050/1050 [==============================] - 15s 14ms/step - loss: 0.0327 - accuracy: 0.9893 - val_loss: 0.0562 - val_accuracy: 0.9826
Epoch 7/100
1050/1050 [==============================] - 15s 14ms/step - loss: 0.0278 - accuracy: 0.9910 - val_loss: 0

In [52]:
data_test=pd.read_csv("test.csv")

In [53]:
X_test = data_test.values.reshape(-1, 28, 28, 1) / 255.0



In [54]:
X_test

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [55]:
# Make predictions on the test set
test_predictions = model.predict(X_test)

875/875 [==============================] - 5s 5ms/step


In [56]:
import numpy as np

In [57]:
test_preds=[]
for i in range(len(test_predictions)):
    test_preds.append(np.argmax(test_predictions[i]))

In [58]:
test_preds

[2,
 0,
 9,
 9,
 3,
 7,
 0,
 3,
 0,
 3,
 5,
 7,
 4,
 0,
 4,
 3,
 3,
 1,
 9,
 0,
 9,
 1,
 1,
 5,
 7,
 4,
 2,
 7,
 4,
 7,
 7,
 5,
 4,
 2,
 6,
 2,
 5,
 5,
 1,
 6,
 7,
 7,
 4,
 9,
 8,
 7,
 8,
 2,
 6,
 7,
 6,
 8,
 8,
 3,
 8,
 2,
 1,
 2,
 2,
 0,
 4,
 1,
 7,
 0,
 0,
 0,
 1,
 9,
 0,
 1,
 6,
 5,
 8,
 8,
 2,
 8,
 9,
 9,
 2,
 3,
 5,
 4,
 1,
 0,
 9,
 2,
 4,
 3,
 6,
 7,
 2,
 0,
 6,
 6,
 1,
 4,
 3,
 9,
 7,
 4,
 0,
 9,
 2,
 0,
 7,
 3,
 0,
 5,
 0,
 8,
 0,
 0,
 4,
 7,
 1,
 7,
 1,
 1,
 3,
 3,
 3,
 7,
 2,
 8,
 6,
 3,
 8,
 7,
 7,
 4,
 3,
 5,
 6,
 0,
 0,
 0,
 3,
 1,
 3,
 6,
 4,
 3,
 4,
 5,
 5,
 8,
 7,
 7,
 2,
 8,
 4,
 3,
 5,
 6,
 5,
 3,
 7,
 5,
 7,
 8,
 3,
 0,
 4,
 5,
 1,
 2,
 7,
 6,
 3,
 0,
 2,
 7,
 8,
 6,
 1,
 3,
 7,
 4,
 1,
 2,
 4,
 8,
 5,
 2,
 4,
 9,
 2,
 1,
 6,
 0,
 6,
 1,
 4,
 9,
 6,
 0,
 9,
 7,
 6,
 9,
 1,
 9,
 0,
 9,
 9,
 0,
 8,
 4,
 6,
 2,
 0,
 9,
 3,
 6,
 3,
 2,
 1,
 6,
 3,
 4,
 2,
 3,
 1,
 2,
 2,
 0,
 4,
 6,
 1,
 0,
 0,
 4,
 9,
 1,
 7,
 3,
 2,
 3,
 8,
 6,
 8,
 6,
 2,
 8,
 5,
 5,
 4,
 8,
 3,
 5,


In [63]:
submission=pd.read_csv("sample_submission.csv")

In [64]:
submission.Label=test_preds

In [65]:
submission.to_csv("submission.csv",index=False)

In [66]:
submission.shape

(28000, 2)

In [74]:
tensorflow.version

<module 'tensorflow._api.v2.version' from 'C:\\Users\\aabir\\AppData\\Roaming\\Python\\Python39\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>

In [75]:
pip3 install tensorflow_decision_forests --upgrade

SyntaxError: invalid syntax (2306888368.py, line 1)

In [78]:
import tensorflow_decision_forests as tfdf

ModuleNotFoundError: No module named 'tensorflow_decision_forests'

In [77]:
!pip install tensorflow tensorflow_decision_forests

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement tensorflow_decision_forests (from versions: none)
ERROR: No matching distribution found for tensorflow_decision_forests


In [79]:
!pip install tensorflow-decision-forests==0.2.0

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement tensorflow-decision-forests==0.2.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-decision-forests==0.2.0


In [1]:
!pip install tensorflow tensorflow_decision_forests

ERROR: Could not find a version that satisfies the requirement tensorflow_decision_forests (from versions: none)
ERROR: No matching distribution found for tensorflow_decision_forests
